### ISSUE TITLE
Question about the initialization of RCM

### ISSUE THREAD

**Issue by liuzhen0212** [JiaxiongQ/NeRC#1]
Hi, thanks for your great work! I have a question about the **initialization of Rendering Color Module (RCM)**?

Since sine activation is used in RCM, is **SIREN initialization** as shown below is required here?

$$W \sim U(-\frac{1}{k}, \frac{1}{k})$$ for the first layer, and 
$$W \sim U(-\sqrt{\frac{6}{k}} / \omega_0, \sqrt{\frac{6}{k}} / \omega_0)$$ for other layers.

**Comment by JiaxiongQ** [comment]
Yes, you are right. We use the default setting of SIREN.
